AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM User and Policy for Kamiwaza EC2 Provisioning'

Resources:
  KamiwazaProvisioningPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: 'KamiwazaEC2ProvisioningPolicy'
      Description: 'Policy for Kamiwaza Deployment Manager to provision EC2 instances'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'EC2Provisioning'
            Effect: 'Allow'
            Action:
              - 'ec2:RunInstances'
              - 'ec2:TerminateInstances'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeInstanceTypes'
              - 'ec2:DescribeImages'
              - 'ec2:DescribeKeyPairs'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeSubnets'
              - 'ec2:DescribeVpcs'
              - 'ec2:DescribeAvailabilityZones'
              - 'ec2:DescribeInstanceAttribute'
              - 'ec2:DescribeVolumes'
              - 'ec2:CreateTags'
              - 'ec2:DeleteTags'
              - 'ec2:ModifyInstanceAttribute'
              - 'ec2:AssociateIamInstanceProfile'
              - 'ec2:DisassociateIamInstanceProfile'
            Resource: '*'
          - Sid: 'NetworkingRequired'
            Effect: 'Allow'
            Action:
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:AuthorizeSecurityGroupEgress'
              - 'ec2:RevokeSecurityGroupIngress'
              - 'ec2:RevokeSecurityGroupEgress'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:DeleteSecurityGroup'
            Resource: '*'
          - Sid: 'TerraformStateManagement'
            Effect: 'Allow'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource:
              - 'arn:aws:s3:::terraform-state-*'
              - 'arn:aws:s3:::terraform-state-*/*'

  KamiwazaProvisioningUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'kamiwaza-provisioner'
      ManagedPolicyArns:
        - !Ref KamiwazaProvisioningPolicy

  KamiwazaProvisioningAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref KamiwazaProvisioningUser

Outputs:
  AccessKeyId:
    Description: 'Access Key ID for Kamiwaza Provisioner'
    Value: !Ref KamiwazaProvisioningAccessKey
  SecretAccessKey:
    Description: 'Secret Access Key for Kamiwaza Provisioner (save this securely!)'
    Value: !GetAtt KamiwazaProvisioningAccessKey.SecretAccessKey
  UserArn:
    Description: 'ARN of the IAM User'
    Value: !GetAtt KamiwazaProvisioningUser.Arn
